version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:14.21
  entrypoint: ["node"]
  working_dir: /root
  restart: always
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-env-defaults: &env
  GTM_CONTAINER_ID: ${GTM_CONTAINER_ID}
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  OMEDA_APP_ID: ${OMEDA_APP_ID-(unset)}
  OMEDA_INPUT_ID: ${OMEDA_INPUT_ID-(unset)}
  OMEDA_GRAPHQL_URI: ${OMEDA_GRAPHQL_URI-https://graphql.omeda.parameter1.com}
  IDENTITYX_API_TOKEN: ${IDENTITYX_API_TOKEN-(unset)}
  # @todo the recaptcha values should be removed (?) once contact-us is moved to core.
  RECAPTCHA_V3_SITE_KEY: ${RECAPTCHA_V3_SITE_KEY-}
  RECAPTCHA_V3_SECRET_KEY: ${RECAPTCHA_V3_SECRET_KEY-}
  BASE_BROWSE_GRAPHQL_URI: ${BASE_BROWSE_GRAPHQL_URI-https://base-browse.virgon.base.parameter1.com/graphql}
  # @todo the sendgrid values should be removed once the @parameter1/base-cms-mailer service is created.
  SENDGRID_API_KEY: ${SENDGRID_API_KEY-(unset)}
  SENDGRID_DEV_TO: developer@endeavorb2b.com
  YARN_CACHE_FOLDER: /.yarn-cache

x-env-virgon: &env-virgon
  GRAPHQL_URI: ${GRAPHQL_URI-https://virgon.graphql.base.parameter1.com}
  OEMBED_URI: ${OEMBED_URI-https://virgon.oembed.base.parameter1.com}
  RSS_URI: ${RSS_URI-https://virgon.rss.base.parameter1.com}
  SITEMAPS_URI: ${SITEMAPS_URI-https://virgon.sitemaps.base.parameter1.com}

x-env-development: &env-development
  GRAPHQL_URI: ${GRAPHQL_URI-http://host.docker.internal:10002}
  OEMBED_URI: ${OEMBED_URI-http://host.docker.internal:10013}
  RSS_URI: ${RSS_URI-http://host.docker.internal:10011}
  SITEMAPS_URI: ${SITEMAPS_URI-http://host.docker.internal:10009}

x-site-command: &site-cmd
  <<: *node
  entrypoint: ["yarn"]
  command: ["dev"]

volumes:
  yarn-cache: {}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  de:
    <<: *site-cmd
    working_dir: /root/sites/diverseeducation.com
    environment:
      <<: [*env, *env-virgon]
      PORT: 80
      EXPOSED_PORT: 9810
      LIVERELOAD_PORT: 19810
      TENANT_KEY: diverse_all
      SITE_ID: 60c281c6d28860bc33464ae0
    ports:
      - "9810:80"
      - "19810:19810"

  dm:
    <<: *site-cmd
    working_dir: /root/sites/diversemilitary.net
    environment:
      <<: [*env, *env-virgon]
      PORT: 80
      EXPOSED_PORT: 9811
      LIVERELOAD_PORT: 19811
      TENANT_KEY: diverse_all
      SITE_ID: 60c28c0dd28860bc334ed723
    ports:
      - "9811:80"
      - "19811:19811"

  dh:
    <<: *site-cmd
    working_dir: /root/sites/divhealth.net
    environment:
      <<: [*env, *env-virgon]
      PORT: 80
      EXPOSED_PORT: 9812
      LIVERELOAD_PORT: 19812
      TENANT_KEY: diverse_all
      SITE_ID: 60c28c4bd28860bc334f485d
    ports:
      - "9812:80"
      - "19812:19812"

  ccn:
    <<: *site-cmd
    working_dir: /root/sites/ccnewsnow.com
    environment:
      <<: [*env, *env-virgon]
      PORT: 80
      EXPOSED_PORT: 9813
      LIVERELOAD_PORT: 19813
      TENANT_KEY: diverse_all
      SITE_ID: 60c28bc3d28860bc334ebcb2
    ports:
      - "9813:80"
      - "19813:19813"
