name: Integration Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-and-test-image:
    uses: parameter1/actions/.github/workflows/website-build-push-test.yml@main
    strategy:
      matrix:
        ###############################################
        #v# Make sure this matches the site matrix! #v#
        ###############################################
        site:
          - { id: 60c28bc3d28860bc334ebcb2, dir: ccnewsnow.com, stack: virgon, account: diverse, tenant: diverse_all, rancher_label: cox-matthews-associates-ccnewsnow.com }
          - { id: 60c281c6d28860bc33464ae0, dir: diverseeducation.com, stack: virgon, account: diverse, tenant: diverse_all, rancher_label: cox-matthews-associates-diverseeducation.com }
          - { id: 60c28c0dd28860bc334ed723, dir: diversemilitary.net, stack: virgon, account: diverse, tenant: diverse_all, rancher_label: cox-matthews-associates-diversemilitary.net }
          - { id: 60c28c4bd28860bc334f485d, dir: divhealth.net, stack: virgon, account: diverse, tenant: diverse_all, rancher_label: cox-matthews-associates-divhealth.net }
        ###############################################
        #^# Make sure this matches the site matrix! #^#
        ###############################################
    with:
      ecr_registry: ${{ vars.AWS_ECR_REGISTRY }}
      site_account: ${{ matrix.site.account }}
      site_dir: ${{ matrix.site.dir }}
      site_version: test
